export const CATEGORY_BROWSER = {
  Vegetables: ["Tomato", "Potato", "Onion", "Cabbage", "Cauliflower", "Chilli", "Brinjal", "Carrot", "Spinach"],
  Fruits: ["Banana", "Grapes", "Pomegranate", "Papaya", "Mango", "Guava", "Apple", "Orange"],
  Pulses: ["Tur", "Chana", "Urad", "Moong", "Masoor", "Horse Gram"],
  Grains: ["Corn", "Wheat", "Rice", "Jowar", "Maize", "Bajra", "Ragi"],
  Spices: ["Turmeric", "Coriander", "Cumin", "Red Chillies", "Black Pepper", "Cloves", "Ginger", "Garlic"],
  Flowers: ["Marigold", "Rose", "Jasmine", "Chrysanthemum"],
  "Non-Edible": ["Tobacco", "Sugarcane", "Cotton"],
  Herbs: ["Tulsi", "Mint", "Curry Leaves", "Lemongrass"],
  Livestock: ["Cow Feed", "Goat Feed", "Poultry Feed"],
  Other: ["Groundnut", "Soybean", "Arecanut", "Coconut"],
};

export const LANGUAGE_OPTIONS = ["English", "Hindi", "Marathi", "Kannada"];

export const TRANSLATIONS = {
  English: {
    home: "Home",
    forFarmers: "For Farmers",
    forBuyers: "For Buyers",
    howItWorks: "How It Works",
    login: "Login",
    register: "Register",
    searchCrops: "Search Live Crops",
    marketplace: "Marketplace",
    buyFresh: "Buy Fresh Produce Directly from Local Farmers",
    viewMap: "View Live Logistics Map",
    logout: "Logout",
    myListings: "My Listings",
    recentOrders: "Recent Orders",
    publishNew: "Publish New",
    enableOffline: "Enable Offline",
    offlineEnabled: "Offline Enabled",
    backToMarketplace: "Back to marketplace",
    farmer: "Farmer",
    retailBuyer: "Retail Buyer",
    selectRole: "Select role",
    fullName: "Full name",
    phoneNumber: "Phone number",
    emailAddress: "Email address",
    location: "Location",
    newUserRegister: "New user? Register",
    alreadyRegisteredLogin: "Already registered? Login",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    continueAs: "Continue as",
    registerAs: "Register",
    farmerHelper: "Farmer login uses phone number only for faster access in the field.",
    buyerHelper: "Buyer login uses email so marketplace orders remain easy to track.",
    lowNetwork: "Works even in low network areas",
    continueNetwork: "Continue into the Green Mandi network with the same low-bandwidth, farmer-first workflow used across the platform.",
    enterPhoneNumber: "Enter phone number",
    enterBuyerEmail: "Enter buyer email",
    optionalEmail: "Optional email for receipts",
    optionalBuyerPhone: "Optional buyer phone",
    translate: "Translate",
    categoriesTitle: "Categories",
    allCategories: "All Categories",
    languageStatus: "Language:",
    heroTitle: "Welcome to Nippani's 1st live agricultural marketplace",
    exploreMarket: "Explore buyer market",
    featureFarmersTitle: "For Farmers",
    featureFarmersBody: "List harvest stock, set prices, and publish even with weak connectivity.",
    featureBuyersTitle: "For Buyers",
    featureBuyersBody: "Search live crops, compare quantity, and place direct bulk orders.",
    featureHowWorksTitle: "How it Works",
    featureHowWorksBody: "Search, discover, order, pay through demo UPI, and track logistics.",
    copyright: "Copyright 2026 Green Mandi. All Rights Reserved.",
    expectedValueLabel: "Expected Value",
    totalListingsLabel: "Total Listings",
    profitCalculatorTitle: "Profit Calculator",
    orderHistoryTitle: "Order History",
    noOrdersHistory: "No completed orders to display.",
    publishYourCrop: "Publish Your Crop",
    marketPrice: "Market price:",
    locationLabel: "Location:",
    chooseQuantity: "Choose Quantity",
    setPrice: "Set Price",
    selectLocation: "Select Location",
    publishListingBtn: "Publish Listing",
    saveOffline: "Save Offline",
    publishing: "Publishing...",
    nearbyRetailersTitle: "Nearby Agro Retailers",
    shopCategoryLabel: "Category:",
    myActiveListings: "My Active Listings",
    viewAll: "View All",
    editListing: "EDIT",
    acceptOrder: "ACCEPT",
    declineOrder: "DECLINE",
    statusActive: "ACTIVE",
    statusCompleted: "COMPLETED",
    newOrderFrom: "New order from",
    orderedLabel: "Ordered",
    availableLabel: "Available",
    marketYardLabel: "Market Yard",
    welcomeBack: "Welcome back,",
    heroSubtitle: "Manage your harvest listings and orders at a glance.",
    estimatedProfit: "Estimated Profit",
    activeItems: "Active Items",
    step1: "1. Choose Your Harvest",
    step2: "2. Choose Quantity",
    step3: "3. Set Price",
    step4: "4. Select Location",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    chatOnWhatsApp: "CHAT ON WHATSAPP",
    syncing: "Syncing...",
    syncNow: "Sync Now",
    pendingSyncMessage: "listing(s) waiting to be synced.",
    ton: "Ton",
    kg: "kg",
    liveUpdates: "Live Updates",
    noOrdersFound: "No orders found yet",
    statusProcessing: "Processing",
    statusAwaitingPayment: "Awaiting Payment",
    statusPaidConfirmed: "Paid & Confirmed",
    utrLabel: "UTR:",
    mapsView: "Maps View",
    pendingSyncLabel: "Pending Sync",
    statusDelivered: "Delivered",
    editListingTitle: "Edit Your Listing",
    checkingAccess: "Checking farmer access...",
    saveName: "Save Name",
    editName: "Edit Name",
    retailer: "Retailer",
    shopLabel: "Shop",
    refreshStats: "Refresh Stats",
  },
  Hindi: {
    home: "होम",
    forFarmers: "किसानों के लिए",
    forBuyers: "खरीदारों के लिए",
    howItWorks: "यह कैसे काम करता है",
    login: "लॉग इन करें",
    register: "पंजीकरण करें",
    searchCrops: "लाइव फ़सलें खोजें",
    marketplace: "बाज़ार",
    buyFresh: "स्थानीय किसानों से सीधे ताज़ा उपज खरीदें",
    viewMap: "लाइव लॉजिस्टिक्स मैप देखें",
    logout: "लॉग आउट",
    myListings: "मेरी सूचियाँ",
    recentOrders: "हाल के आदेश",
    publishNew: "नया प्रकाशित करें",
    enableOffline: "ऑफ़लाइन सक्षम करें",
    offlineEnabled: "ऑफ़लाइन सक्षम है",
    backToMarketplace: "बाज़ार पर वापस जाएँ",
    farmer: "किसान",
    retailBuyer: "खुदरा खरीदार",
    selectRole: "भूमिका चुनें",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    emailAddress: "ईमेल पता",
    location: "स्थान",
    newUserRegister: "नया उपयोगकर्ता? पंजीकरण करें",
    alreadyRegisteredLogin: "पहले से पंजीकृत? लॉग इन करें",
    loggingIn: "लॉग इन हो रहा है...",
    creatingAccount: "खाता बन रहा है...",
    continueAs: "के रूप में जारी रखें",
    registerAs: "के रूप में पंजीकरण करें",
    farmerHelper: "किसान लॉगिन क्षेत्र में तेज पहुंच के लिए केवल फोन नंबर का उपयोग करता है।",
    buyerHelper: "खरीदार लॉगिन ईमेल का उपयोग करता है ताकि बाजार के आदेशों को ट्रैक करना आसान रहे।",
    lowNetwork: "कम नेटवर्क वाले क्षेत्रों में भी काम करता है",
    continueNetwork: "मंच में उपयोग किए जाने वाले समान कम-बैंडविड्थ, किसान-प्रथम वर्कफ़्लो के साथ ग्रीन मंडी नेटवर्क में जारी रखें।",
    enterPhoneNumber: "फ़ोन नंबर दर्ज करें",
    enterBuyerEmail: "खरीदार ईमेल दर्ज करें",
    optionalEmail: "रसीद के लिए वैकल्पिक ईमेल",
    optionalBuyerPhone: "वैकल्पिक खरीदार फोन",
    translate: "अनुवाद करें",
    categoriesTitle: "श्रेणियाँ",
    allCategories: "सभी श्रेणियां",
    languageStatus: "भाषा:",
    heroTitle: "निप्पानी के पहले लाइव कृषि बाजार में आपका स्वागत है",
    exploreMarket: "खरीदार बाजार का अन्वेषण करें",
    featureFarmersTitle: "किसानों के लिए",
    featureFarmersBody: "फसल स्टॉक सूचीबद्ध करें, कीमतें निर्धारित करें, और कमजोर कनेक्टिविटी के बावजूद प्रकाशित करें।",
    featureBuyersTitle: "खरीदारों के लिए",
    featureBuyersBody: "लाइव फसलें खोजें, मात्रा की तुलना करें, और सीधे बल्क ऑर्डर दें।",
    featureHowWorksTitle: "यह कैसे काम करता है",
    featureHowWorksBody: "खोजें, पता लगाएं, ऑर्डर करें, डेमो यूपीआई के माध्यम से भुगतान करें और लॉजिस्टिक्स ट्रैक करें।",
    copyright: "कॉपीराइट २०२६ ग्रीन मंडी। सभी अधिकार सुरक्षित।",
    expectedValueLabel: "अपेक्षित मूल्य",
    totalListingsLabel: "कुल सूची",
    profitCalculatorTitle: "लाभ कैलकुलेटर",
    orderHistoryTitle: "ऑर्डर इतिहास",
    noOrdersHistory: "दिखाने के लिए कोई पूर्ण आदेश नहीं।",
    publishYourCrop: "अपनी फसल प्रकाशित करें",
    marketPrice: "बाजार मूल्य:",
    locationLabel: "स्थान:",
    chooseQuantity: "मात्रा चुनें",
    setPrice: "मूल्य निर्धारित करें",
    selectLocation: "स्थान का चयन करें",
    publishListingBtn: "सूचीकरण प्रकाशित करें",
    saveOffline: "ऑफ़लाइन सहेजें",
    publishing: "प्रकाशित हो रहा है...",
    nearbyRetailersTitle: "आस-पास के कृषि विक्रेता",
    shopCategoryLabel: "श्रेणी:",
    myActiveListings: "मेरी सक्रिय सूचियाँ",
    viewAll: "सभी देखें",
    editListing: "संपादित करें",
    acceptOrder: "स्वीकार करें",
    declineOrder: "अस्वीकार करें",
    statusActive: "सक्रिय",
    statusCompleted: "पूरा हुआ",
    newOrderFrom: "नया ऑर्डर",
    orderedLabel: "ऑर्डर किया गया",
    availableLabel: "उपलब्ध",
    marketYardLabel: "मार्केट यार्ड",
    welcomeBack: "वापस स्वागत है,",
    heroSubtitle: "अपनी फसल लिस्टिंग और ऑर्डर एक नज़र में प्रबंधित करें।",
    estimatedProfit: "अनुमानित लाभ",
    activeItems: "सक्रिय आइटम",
    step1: "1. अपनी फसल चुनें",
    step2: "2. मात्रा चुनें",
    step3: "3. मूल्य निर्धारित करें",
    step4: "4. स्थान चुनें",
    saveChanges: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    chatOnWhatsApp: "व्हाट्सएप पर चैट करें",
    syncing: "सिंक हो रहा है...",
    syncNow: "अभी सिंक करें",
    pendingSyncMessage: "सूची (सूचियां) सिंक होने की प्रतीक्षा कर रही हैं।",
    ton: "टन",
    kg: "किलो",
    liveUpdates: "लाइव अपडेट",
    noOrdersFound: "अभी तक कोई ऑर्डर नहीं मिला",
    statusProcessing: "प्रसंस्करण जारी है",
    statusAwaitingPayment: "भुगतान की प्रतीक्षा है",
    statusPaidConfirmed: "भुगतान किया गया और पुष्टि की गई",
    utrLabel: "यूटीआर:",
    mapsView: "नक्शा दृश्य",
    pendingSyncLabel: "लंबित सिंक",
    statusDelivered: "वितरित",
    editListingTitle: "अपनी सूची संपादित करें",
    checkingAccess: "किसान पहुंच की जाँच हो रही है...",
    saveName: "नाम सहेजें",
    editName: "नाम संपादित करें",
    retailer: "विक्रेता",
    shopLabel: "दुकान",
    refreshStats: "आंकड़े ताज़ा करें",
  },
  Marathi: {
    home: "मुख्यपृष्ठ",
    forFarmers: "शेतकऱ्यांसाठी",
    forBuyers: "खरेदीदारांसाठी",
    howItWorks: "हे कसे कार्य करते",
    login: "लॉगिन करा",
    register: "नोंदणी करा",
    searchCrops: "थेट पिके शोधा",
    marketplace: "बाजारपेठ",
    buyFresh: "स्थानिक शेतकऱ्यांकडून थेट ताजे उत्पादन खरेदी करा",
    viewMap: "थेट लॉजिस्टिक नकाशा पहा",
    logout: "लॉगआउट",
    myListings: "माझी सूची",
    recentOrders: "अलीकडील ऑर्डर्स",
    publishNew: "नवीन प्रकाशित करा",
    enableOffline: "ऑफलाइन सक्षम करा",
    offlineEnabled: "ऑफलाइन सक्षम आहे",
    backToMarketplace: "बाजारपेठेत परत जा",
    farmer: "शेतकरी",
    retailBuyer: "किरकोळ खरेदीदार",
    selectRole: "भूमिका निवडा",
    fullName: "पूर्ण नाव",
    phoneNumber: "फोन नंबर",
    emailAddress: "ईमेल पत्ता",
    location: "ठिकाण",
    newUserRegister: "नवीन वापरकर्ता? नोंदणी करा",
    alreadyRegisteredLogin: "आधीच नोंदणीकृत आहात? लॉगिन करा",
    loggingIn: "लॉगिन करत आहे...",
    creatingAccount: "खाते तयार करत आहे...",
    continueAs: "म्हणून सुरू ठेवा",
    registerAs: "म्हणून नोंदणी करा",
    farmerHelper: "शेतकरी लॉगिन क्षेत्रात जलद प्रवेशासाठी फक्त फोन नंबर वापरते.",
    buyerHelper: "खरेदीदार लॉगिन ईमेल वापरतो जेणेकरून बाजारपेठेतील ऑर्डर्स ट्रॅक करणे सोपे राहील.",
    lowNetwork: "कमी नेटवर्क असलेल्या भागातही काम करते",
    continueNetwork: "प्लॅटफॉर्मवर वापरल्या जाणाऱ्या त्याच कमी-बँडविड्थ, शेतकरी-प्रथम वर्कफ्लोसह ग्रीन मंडी नेटवर्कमध्ये सुरू ठेवा.",
    enterPhoneNumber: "फोन नंबर प्रविष्ट करा",
    enterBuyerEmail: "खरेदीदार ईमेल प्रविष्ट करा",
    optionalEmail: "पावतीसाठी पर्यायी ईमेल",
    optionalBuyerPhone: "पर्यायी खरेदीदार फोन",
    translate: "भाषांतर करा",
    categoriesTitle: "श्रेण्या",
    allCategories: "सर्व श्रेण्या",
    languageStatus: "भाषा:",
    heroTitle: "निपाणीच्या पहिल्या लाइव्ह कृषी बाजारात आपले स्वागत आहे",
    exploreMarket: "खरेदीदार बाजार एक्सप्लोर करा",
    featureFarmersTitle: "शेतकऱ्यांसाठी",
    featureFarmersBody: "पीक साठा सूचीबद्ध करा, किंमती निश्चित करा आणि कमकुवत कनेक्टिव्हिटीसह देखील प्रकाशित करा.",
    featureBuyersTitle: "खरेदीदारांसाठी",
    featureBuyersBody: "थेट पिके शोधा, परिमाणांची तुलना करा आणि थेट घाऊक ऑर्डर्स द्या.",
    featureHowWorksTitle: "हे कसे कार्य करते",
    featureHowWorksBody: "शोधा, एक्सप्लोर करा, ऑर्डर करा, डेमो UPI द्वारे पेमेंट करा आणि लॉजिस्टिक्स ट्रॅक करा.",
    copyright: "कॉपीराइट २०२६ ग्रीन मंडी. सर्व हक्क राखीव.",
    expectedValueLabel: "अपेक्षित मूल्य",
    totalListingsLabel: "एकूण सूची",
    profitCalculatorTitle: "नफा कॅल्क्युलेटर",
    orderHistoryTitle: "ऑर्डर इतिहास",
    noOrdersHistory: "दर्शविण्यासाठी कोणतेही पूर्ण झालेले ऑर्डर नाहीत.",
    publishYourCrop: "तुमचे पीक प्रकाशित करा",
    marketPrice: "बाजारभाव:",
    locationLabel: "स्थान:",
    chooseQuantity: "प्रमाण निवडा",
    setPrice: "किंमत निश्चित करा",
    selectLocation: "स्थान निवडा",
    publishListingBtn: "सूचीकरण प्रकाशित करा",
    saveOffline: "ऑफलाइन सेव्ह करा",
    publishing: "प्रकाशित होत आहे...",
    nearbyRetailersTitle: "जवळपासचे कृषी विक्रेते",
    shopCategoryLabel: "श्रेणी:",
    myActiveListings: "माझ्या सक्रिय सूची",
    viewAll: "सर्व पहा",
    editListing: "संपादित करा",
    acceptOrder: "स्वीकारा",
    declineOrder: "नकारा",
    statusActive: "सक्रिय",
    statusCompleted: "पूर्ण",
    newOrderFrom: "नवीन ऑर्डर",
    orderedLabel: "ऑर्डर केले",
    availableLabel: "उपलब्ध",
    marketYardLabel: "मार्केट यार्ड",
    welcomeBack: "पुन्हा स्वागत आहे,",
    heroSubtitle: "आपल्या पिकांची यादी आणि ऑर्डर एका दृष्टीक्षेपात व्यवस्थापित करा.",
    estimatedProfit: "अंदाजित नफा",
    activeItems: "सक्रिय वस्तू",
    step1: "1. आपले पीक निवडा",
    step2: "2. प्रमाण निवडा",
    step3: "3. किंमत निश्चित करा",
    step4: "4. स्थान निवडा",
    saveChanges: "बदल जतन करा",
    cancel: "रद्द करा",
    chatOnWhatsApp: "व्हॉट्सॲपवर चॅट करा",
    syncing: "सिंक होत आहे...",
    syncNow: "आता सिंक करा",
    pendingSyncMessage: "सूची (सूची) सिंक होण्याची वाट पाहत आहे.",
    ton: "टन",
    kg: "किलो",
    liveUpdates: "थेट अद्यतने",
    noOrdersFound: "आत्तापर्यंत कोणतेही ऑर्डर सापडले नाहीत.",
    statusProcessing: "प्रक्रिया करत आहे",
    statusAwaitingPayment: "पेमेंटची वाट पाहत आहे",
    statusPaidConfirmed: "भरले आणि पुष्टी केली",
    utrLabel: "यूटीआर:",
    mapsView: "नकाशा दृश्य",
    pendingSyncLabel: "प्रलंबित सिंक",
    statusDelivered: "वितरित",
    editListingTitle: "आपली सूची संपादित करा",
    checkingAccess: "शेतकरी प्रवेश तपासत आहे...",
    saveName: "नाव जतन करा",
    editName: "नाव संपादित करा",
    retailer: "विक्रेता",
    shopLabel: "दुकान",
    refreshStats: "आकडेवारी रिफ्रेश करा",
  },
  Kannada: {
    home: "ಮುಖಪುಟ",
    forFarmers: "ರೈತರಿಗಾಗಿ",
    forBuyers: "ಖರೀದಿದಾರರಿಗಾಗಿ",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    searchCrops: "ಲೈವ್ ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    buyFresh: "ಸ್ಥಳೀಯ ರೈತರಿಂದ ನೇರವಾಗಿ ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಖರೀದಿಸಿ",
    viewMap: "ಲೈವ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ನಕ್ಷೆಯನ್ನು ವೀಕ್ಷಿಸಿ",
    logout: "ಲಾಗೌಟ್",
    myListings: "ನನ್ನ ಪಟ್ಟಿಗಳು",
    recentOrders: "ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳು",
    publishNew: "ಹೊಸದನ್ನು ಪ್ರಕಟಿಸಿ",
    enableOffline: "ಆಫ್‌ಲೈನ್ ಸಕ್ರಿಯಗೊಳಿಸಿ",
    offlineEnabled: "ಆಫ್‌ಲೈನ್ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    backToMarketplace: "ಮಾರುಕಟ್ಟೆಗೆ ಹಿಂತಿರುಗಿ",
    farmer: "ರೈತ",
    retailBuyer: "ಚಿಲ್ಲರೆ ಖರೀದಿದಾರ",
    selectRole: "ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    location: "ಸ್ಥಳ",
    newUserRegister: "ಹೊಸ ಬಳಕೆದಾರರೇ? ನೋಂದಾಯಿಸಿ",
    alreadyRegisteredLogin: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    loggingIn: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
    creatingAccount: "ಖಾತೆಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    continueAs: "ಹಾಗೆ ಮುಂದುವರಿಯಿರಿ",
    registerAs: "ನೋಂದಾಯಿಸಿ",
    farmerHelper: "ಕ್ಷೇತ್ರದಲ್ಲಿ ವೇಗವಾಗಿ ಪ್ರವೇಶಿಸಲು ರೈತ ಲಾಗಿನ್ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಮಾತ್ರ ಬಳಸುತ್ತದೆ.",
    buyerHelper: "ಮಾರುಕಟ್ಟೆಯ ಆರ್ಡರ್‌ಗಳನ್ನು ಸುಲಭವಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಖರೀದಿದಾರರ ಲಾಗಿನ್ ಇಮೇಲ್ ಅನ್ನು ಬಳಸುತ್ತದೆ.",
    lowNetwork: "ಕಡಿಮೆ ನೆಟ್‌ವರ್ಕ್ ಪ್ರದೇಶಗಳಲ್ಲೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    continueNetwork: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಾದ್ಯಂತ ಬಳಸಲಾಗುವ ಅದೇ ಕಡಿಮೆ-ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್, ರೈತ-ಮೊದಲ ವರ್ಕ್‌ಫ್ಲೋನೊಂದಿಗೆ ಗ್ರೀನ್ ಮಂಡಿ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ.",
    enterPhoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    enterBuyerEmail: "ಖರೀದಿದಾರರ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    optionalEmail: "ರಸೀದಿಗಳಿಗಾಗಿ ಐಚ್ಛಿಕ ಇಮೇಲ್",
    optionalBuyerPhone: "ಐಚ್ಛಿಕ ಖರೀದಿದಾರರ ಫೋನ್",
    translate: "ಅನುವಾದಿಸಿ",
    categoriesTitle: "ವರ್ಗಗಳು",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    languageStatus: "ಭಾಷೆ:",
    heroTitle: "ನಿಪ್ಪಾಣಿಯ ಮೊದಲ ಲೈವ್ ಕೃಷಿ ಮಾರುಕಟ್ಟೆಗೆ ಸ್ವಾಗತ",
    exploreMarket: "ಖರೀದಿದಾರರ ಮಾರುಕಟ್ಟೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",
    featureFarmersTitle: "ರೈತರಿಗಾಗಿ",
    featureFarmersBody: "ಬೆಳೆ ಸ್ಟಾಕ್ ಅನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, ಬೆಲೆಗಳನ್ನು ನಿಗದಿಪಡಿಸಿ ಮತ್ತು ದುರ್ಬಲ ಸಂಪರ್ಕದೊಂದಿಗೆ ಪ್ರಕಟಿಸಿ.",
    featureBuyersTitle: "ಖರೀದಿದಾರರಿಗಾಗಿ",
    featureBuyersBody: "ಲೈವ್ ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ, ಪ್ರಮಾಣವನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ ಮತ್ತು ನೇರ ಸಗಟು ಆರ್ಡರ್‌ಗಳನ್ನು ನೀಡಿ.",
    featureHowWorksTitle: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    featureHowWorksBody: "ಹುಡುಕಿ, ಅನ್ವೇಷಿಸಿ, ಆರ್ಡರ್ ಮಾಡಿ, ಡೆಮೊ UPI ಮೂಲಕ ಪಾವತಿಸಿ ಮತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    copyright: "ಕಾಪಿರೈಟ್ 2026 ಗ್ರೀನ್ ಮಂಡಿ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    expectedValueLabel: "ನಿರೀಕ್ಷಿತ ಮೌಲ್ಯ",
    totalListingsLabel: "ಒಟ್ಟು ಪಟ್ಟಿಗಳು",
    profitCalculatorTitle: "ಲಾಭ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    orderHistoryTitle: "ಆರ್ಡರ್ ಇತಿಹಾಸ",
    noOrdersHistory: "ಪ್ರದರ್ಶಿಸಲು ಯಾವುದೇ ಪೂರ್ಣಗೊಂಡ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ.",
    publishYourCrop: "ನಿಮ್ಮ ಬೆಳೆಯನ್ನು ಪ್ರಕಟಿಸಿ",
    marketPrice: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ:",
    locationLabel: "ಸ್ಥಳ:",
    chooseQuantity: "ಪ್ರಮಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    setPrice: "ಬೆಲೆ ನಿಗದಿಪಡಿಸಿ",
    selectLocation: "ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    publishListingBtn: "ಪಟ್ಟಿಯನ್ನು ಪ್ರಕಟಿಸಿ",
    saveOffline: "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಸಿ",
    publishing: "ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ...",
    nearbyRetailersTitle: "ಹತ್ತಿರದ ಆಗ್ರೋ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿಗಳು",
    shopCategoryLabel: "ವರ್ಗ:",
    myActiveListings: "ನನ್ನ ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    editListing: "ತಿದ್ದಿ",
    acceptOrder: "ಒಪ್ಪಿಕೊಳ್ಳಿ",
    declineOrder: "ತಿರಸ್ಕರಿಸಿ",
    statusActive: "ಸಕ್ರಿಯ",
    statusCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    newOrderFrom: "ಇವರಿಂದ ಹೊಸ ಆರ್ಡರ್",
    orderedLabel: "ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ",
    availableLabel: "ಲಭ್ಯವಿದೆ",
    marketYardLabel: "ಮಾರುಕಟ್ಟೆ ಯಾರ್ಡ್",
    welcomeBack: "ಮತ್ತೆ ಸುಸ್ವಾಗತ,",
    heroSubtitle: "ನಿಮ್ಮ ಬೆಳೆ ಪಟ್ಟಿಗಳು ಮತ್ತು ಆರ್ಡರ್‌ಗಳನ್ನು ಒಂದು ನೋಟದಲ್ಲಿ ನಿರ್ವಹಿಸಿ.",
    estimatedProfit: "ನಿರೀಕ್ಷಿತ ಲಾಭ",
    activeItems: "ಸಕ್ರಿಯ ಐಟಂಗಳು",
    step1: "1. ನಿಮ್ಮ ಬೆಳೆಯನ್ನು ಆರಿಸಿ",
    step2: "2. ಪ್ರಮಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    step3: "3. ಬೆಲೆ ನಿಗದಿಪಡಿಸಿ",
    step4: "4. ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    chatOnWhatsApp: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಚಾಟ್ ಮಾಡಿ",
    syncing: "ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",
    syncNow: "ಈಗ ಸಿಂಕ್ ಮಾಡಿ",
    pendingSyncMessage: "ಪಟ್ಟಿಗಳು ಸಿಂಕ್ ಆಗಲು ಕಾಯುತ್ತಿವೆ.",
    ton: "ಟನ್",
    kg: "ಕೆಜಿ",
    liveUpdates: "ಲೈವ್ ಅಪ್‌ಡೇಟ್",
    noOrdersFound: "ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    statusProcessing: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    statusAwaitingPayment: "ಪಾವತಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    statusPaidConfirmed: "ಪಾವತಿಸಲಾಗಿದೆ ಮತ್ತು ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    utrLabel: "ಯುಟಿಆರ್:",
    mapsView: "ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ",
    pendingSyncLabel: "ಸಿಂಕ್ ಬಾಕಿ ಇದೆ",
    statusDelivered: "ತಲುಪಿಸಲಾಗಿದೆ",
    editListingTitle: "ನಿಮ್ಮ ಪಟ್ಟಿಯನ್ನು ತಿದ್ದಿ",
    checkingAccess: "ರೈತ ಪ್ರವೇಶವನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    saveName: "ಹೆಸರನ್ನು ಉಳಿಸಿ",
    editName: "ಹೆಸರನ್ನು ತಿದ್ದಿ",
    retailer: "ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿ",
    shopLabel: "ಅಂಗಡಿ",
    refreshStats: "ಅಂಕಿಅಂಶಗಳನ್ನು ನವೀಕರಿಸಿ",
  }
};
